export const RELEASED_PIN = 'b81aff7f323b47ae0747ff33571f3c9bc8ec60cb';

/** A complete minimal caller; schedules and refresh caching live in the linked full example. */
export function starterWorkflow(pin: string) {
  if (!/^[a-f0-9]{40}$/.test(pin)) throw new Error('A full action commit is required');
  return [
    'name: Skillz Shield',
    'on:',
    '  pull_request:',
    '  push:',
    '    branches: [main]',
    '  workflow_dispatch:',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
    '  skills:',
    '    runs-on: ubuntu-latest',
    '    timeout-minutes: 60',
    '    steps:',
    '      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1',
    '        with:',
    '          fetch-depth: 0',
    '          persist-credentials: false',
    '      - name: Select skill packages',
    '        id: plan',
    `        uses: OKHP3/skillz-shield@${pin}`,
    '        with:',
    '          mode: plan',
    '          state: ${{ runner.temp }}/skillz-shield-state',
    "          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event_name == 'push' && github.event.before || '' }}",
    "          full: ${{ github.event_name == 'workflow_dispatch' }}",
    '      - name: Resolve stable scanner releases',
    "        if: steps.plan.outputs.scan == 'true'",
    `        uses: OKHP3/skillz-shield@${pin}`,
    '        env:',
    '          GH_TOKEN: ${{ github.token }}',
    '        with:',
    '          mode: resolve',
    '          state: ${{ runner.temp }}/skillz-shield-state',
    '      - name: Install verified engines',
    "        if: steps.plan.outputs.scan == 'true'",
    `        uses: OKHP3/skillz-shield@${pin}`,
    '        with:',
    '          mode: install',
    '          state: ${{ runner.temp }}/skillz-shield-state',
    '      - name: Scan selected skills',
    "        if: steps.plan.outputs.scan == 'true'",
    `        uses: OKHP3/skillz-shield@${pin}`,
    '        with:',
    '          mode: scan',
    '          state: ${{ runner.temp }}/skillz-shield-state',
    '      - name: Keep sanitized evidence',
    '        if: always()',
    '        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2',
    '        with:',
    '          name: skillz-shield-evidence',
    '          path: |',
    '            ${{ runner.temp }}/skillz-shield-state/plan.json',
    '            ${{ runner.temp }}/skillz-shield-state/pins.json',
    '            ${{ runner.temp }}/skillz-shield-state/report.json',
    '          if-no-files-found: ignore',
    '          retention-days: 14',
    '',
  ].join('\n');
}
